# Module 1: Building a simple torch based NN model

In [68]:
import torch

In [69]:
torch.manual_seed(7)

In [70]:
def activation(x):
    """ Sigmoid activation function
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [71]:
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [72]:
output = activation(torch.sum(features * weights) + bias)

In [73]:
output

tensor([[0.1595]])

## Why not torch.matmul() ?

In [74]:
features.shape, weights.shape, bias.shape

(torch.Size([1, 5]), torch.Size([1, 5]), torch.Size([1, 1]))

In [75]:
weights = weights.reshape(5, 1)

In [76]:
WX = torch.matmul(features, weights)
WX

tensor([[-1.9796]])

In [77]:
activation(WX + bias)

tensor([[0.1595]])

#### Perfect!

## Stack them up!

In [78]:
features = torch.randn((1,3))

# size of each layer of network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

In [79]:
# internal layer weights
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

In [80]:
# bais terms
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [81]:
# building the network

In [82]:
features.shape, W1.shape, B1.shape

(torch.Size([1, 3]), torch.Size([3, 2]), torch.Size([1, 2]))

In [83]:
W2.shape, B2.shape

(torch.Size([2, 1]), torch.Size([1, 1]))

In [84]:
h = activation(torch.mm(features,W1) + B1)
y = activation(torch.mm(h, W2) + B2)

In [85]:
y

tensor([[0.8805]])

# Module 2: Numpy to Torch and Back